version: "3.8"
services:

  api:
    image: sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.2_13_1.9.9_3.4.1
    volumes:
      - .:/app
      - .env.docker:/app/.env
    working_dir: /app
    entrypoint: sbt backend/run
    ports:
      - 9669:9669
    networks:
      - fide
    profiles:
      - sbt

  db:
    image: postgres:16.2-alpine3.19
    container_name: fide_postgres
    volumes:
      - ./.containers_data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fide
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dummy
    ports:
      - 5432:5432
    networks:
      - fide
    restart: unless-stopped

volumes:
  .containers-data: {}

networks:
  fide:
    driver: bridge
