name: fide

services:

  api:
    image: ghcr.io/sergioglorias/fide:main
    volumes: 
      - .env.docker:/app/.env
    ports:
      - 9669:9669
    networks:
      - fide

  db:
    image: postgres:16.2-alpine3.19
    container_name: fide_postgres
    volumes:
      - ./.containers_data/postgres:/var/lib/postgresql/data
    environment:
      # VAR is the ".env"
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - fide
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: fide_adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8180:8080
    networks:
      - fide
    restart: unless-stopped

volumes:
  .containers-data: {}

networks:
  fide:
    driver: bridge
